INSERT INTO henkilo VALUES ('Niilo', 'Nessukka', 'niilo@jippii.lol', '221c0a20e7a30c2835c1b3fcaa432e7a', 'admin');
INSERT INTO henkilo VALUES ('Sirpa', 'Särpäle', 'sirpa@jihuu.lol', '48ece95de0e6393b476eaac1bbeb1390', 'admin');

INSERT INTO henkilo VALUES ('Heidi', 'Hipsiäinen', 'hipsi@hapsi.lol', '1fc1f6ee27300e5533aa172e727c4e33', 'opettaja');
INSERT INTO henkilo VALUES ('Waldemar', 'Viiksi', 'vallu@viichet.lol', '56f5f303e29b42dd212a56dd60bd2521', 'opettaja');
INSERT INTO henkilo VALUES ('Risto', 'Raparperi', '2', '29623418a18355aad1fd430208110931', 'opettaja');

INSERT INTO henkilo VALUES ('Jorma', 'Junttura', 'luukku@posti.lol', 'bb0672262584c582751df3358c795445', 'vastuuhenkilö');
INSERT INTO henkilo VALUES ('Laiska', 'Mato', '3', 'fc9f7a3782985cf2998bc25e27f24c2e', 'vastuuhenkilö');

INSERT INTO kurssi VALUES (6, 'Ohjelmoinnin varusteet', 4, 2012);
INSERT INTO kurssi VALUES (6, 'Ohjelmoinnin pitkokurssi', 3, 2012);
INSERT INTO kurssi VALUES (4, 'Johdatus punktionaaliseen ohjelmointiin', 4, 2012);
INSERT INTO kurssi VALUES (6, 'Kahvinkeiton alkeet', 1, 2008);

INSERT INTO kurssikysely VALUES (1, 'OhVa-kysely', 6, TRUE, TRUE);
INSERT INTO kurssikysely VALUES (2, 'OhPi-kysely', 6, FALSE, FALSE);
INSERT INTO kurssikysely VALUES (3, 'JPO-kysely', 4, TRUE, TRUE);
INSERT INTO kurssikysely VALUES (4, 'KaAl-kysely', 6, FALSE, TRUE);

INSERT INTO kysymys VALUES ('Arvioi kurssin mielekkyyttä asteikolla 1-5.', 1);
INSERT INTO kysymys VALUES ('Olivatko tehtävät sopivia?', 1);
INSERT INTO kysymys VALUES ('Oliko luennoitsijalla hieno paita?', 1);
INSERT INTO kysymys VALUES ('Minkä arvosanan annat kurssista?', 1);
INSERT INTO kysymys VALUES ('Miten tylsää luennoilla oli?', 2);
INSERT INTO kysymys VALUES ('Opitko mitään kurssista?', 2);
INSERT INTO kysymys VALUES ('Kävitkö luennoilla? (1 = et kertaakaan, 5 = aina)', 2);
INSERT INTO kysymys VALUES ('Minkä arvosanan annat kurssista?', 2);
INSERT INTO kysymys VALUES ('Olivatko tehtävät haasteellisia?', 3);
INSERT INTO kysymys VALUES ('Mitkä fiilikset? (1 = huonot, 5 = mahtavat)', 3);
INSERT INTO kysymys VALUES ('Osaatko nyt ohjelmoida punktionaalisesti? (1 = et :(, 5 = täydellisesti)', 3);
INSERT INTO kysymys VALUES ('Minkä arvosanan annat kurssista?', 3);
INSERT INTO kysymys VALUES ('Opitko erottamaan tummat kavipavut vaaleista?', 4);
INSERT INTO kysymys VALUES ('Aiotko ottaa kahvinkeiton syventävän jatkokurssin?', 4);
INSERT INTO kysymys VALUES ('Hyödyitkö kurssista?', 4);

INSERT INTO kommentti VALUES ('ihan huano kurssi. tiatokoneet on tyhmii.', 1, 1);
INSERT INTO kommentti VALUES ('Tosi kivoja tehtäviä! :))', 2, 1);
INSERT INTO kommentti VALUES ('Plääh, ihan huonoja.', 2, 1);
INSERT INTO kommentti VALUES ('JOOOOOO!', 3, 1);
INSERT INTO kommentti VALUES ('Kurssi oli ihan jees.', 1, 1);
INSERT INTO kommentti VALUES ('Liian työläs, ei ollu!', 1, 1);
INSERT INTO kommentti VALUES ('Ei!!!11', 2, 1);
INSERT INTO kommentti VALUES ('Vähä liian kiree mun makuun :P', 3, 1);
INSERT INTO kommentti VALUES ('Tyhmään kysymykseen tyhmä vastaus', 3, 1);
INSERT INTO kommentti VALUES ('En kiinnittäny huomiota, tämä paha? xDDDD', 3, 1);
INSERT INTO kommentti VALUES ('Varmaa te tällästä kysytte -___-', 3, 1);
INSERT INTO kommentti VALUES ('Asteikolla 1-5 antaisin 6.', 4, 1);
INSERT INTO kommentti VALUES ('Ei, pelasin miinaharavaa ^^', 5, 2);
INSERT INTO kommentti VALUES ('Opin tajuamaan kuinka paljon mulla on vielä opittavaa', 6, 2);
INSERT INTO kommentti VALUES ('En, koska moon koodannu 10v javaa työkseni', 6, 2);
INSERT INTO kommentti VALUES ('Opin tekemään if-lauseen!', 6, 2);
INSERT INTO kommentti VALUES ('Olisin käyny mut olin kipee koko periodin', 7, 2);
INSERT INTO kommentti VALUES ('En, jäi joululomafiilis päälle eikä pygenny :DDD', 7, 2);
INSERT INTO kommentti VALUES ('Osa tehtävistä oli mahdottomia', 9, 3);
INSERT INTO kommentti VALUES ('Ei, tein kaikki tehtävät 10 eri ohjelmointikielellä kun oli tylsää ja liian helppoa. Voisitte jatkossa laittaa vähän haasteellisempia kysymyksiä', 10, 3);
INSERT INTO kommentti VALUES ('Riippuu arvosanasta.', 10, 3);
INSERT INTO kommentti VALUES ('Kiinnostava kurssi oli.', 12, 3);
INSERT INTO kommentti VALUES ('En päässyt edes kokeesta läpi', 13, 4);
INSERT INTO kommentti VALUES ('Ehdottomasti, se on hieno meriitti CV:ssä', 14, 4);

INSERT INTO vastaus VALUES (1, 5, 1);
INSERT INTO vastaus VALUES (1, 5, 1);
INSERT INTO vastaus VALUES (1, 4, 1);
INSERT INTO vastaus VALUES (1, 4, 1);
INSERT INTO vastaus VALUES (1, 3, 1);
INSERT INTO vastaus VALUES (1, 1, 1);
INSERT INTO vastaus VALUES (1, 1, 1);
INSERT INTO vastaus VALUES (1, 1, 1);
INSERT INTO vastaus VALUES (2, 5, 1);
INSERT INTO vastaus VALUES (2, 5, 1);
INSERT INTO vastaus VALUES (2, 3, 1);
INSERT INTO vastaus VALUES (2, 1, 1);
INSERT INTO vastaus VALUES (2, 1, 1);
INSERT INTO vastaus VALUES (2, 1, 1);
INSERT INTO vastaus VALUES (2, 1, 1);
INSERT INTO vastaus VALUES (3, 5, 1);
INSERT INTO vastaus VALUES (3, 2, 1);
INSERT INTO vastaus VALUES (3, 3, 1);
INSERT INTO vastaus VALUES (4, 1, 1);
INSERT INTO vastaus VALUES (4, 1, 1);
INSERT INTO vastaus VALUES (5, 2, 2);
INSERT INTO vastaus VALUES (6, 3, 2);
INSERT INTO vastaus VALUES (7, 2, 2);
INSERT INTO vastaus VALUES (8, 1, 2);
INSERT INTO vastaus VALUES (8, 1, 2);
INSERT INTO vastaus VALUES (8, 2, 2);
INSERT INTO vastaus VALUES (8, 2, 2);
INSERT INTO vastaus VALUES (9, 1, 3);
INSERT INTO vastaus VALUES (9, 2, 3);
INSERT INTO vastaus VALUES (9, 2, 3);
INSERT INTO vastaus VALUES (9, 5, 3);
INSERT INTO vastaus VALUES (10, 1, 3);
INSERT INTO vastaus VALUES (10, 4, 3);
INSERT INTO vastaus VALUES (10, 5, 3);
INSERT INTO vastaus VALUES (10, 5, 3);
INSERT INTO vastaus VALUES (11, 1, 3);
INSERT INTO vastaus VALUES (11, 4, 3);
INSERT INTO vastaus VALUES (11, 5, 3);
INSERT INTO vastaus VALUES (12, 3, 3);
INSERT INTO vastaus VALUES (13, 4, 4);
INSERT INTO vastaus VALUES (13, 4, 4);
INSERT INTO vastaus VALUES (13, 4, 4);
INSERT INTO vastaus VALUES (14, 1, 4);
INSERT INTO vastaus VALUES (14, 5, 4);
INSERT INTO vastaus VALUES (15, 2, 4);
INSERT INTO vastaus VALUES (15, 2, 4);
INSERT INTO vastaus VALUES (15, 3, 4);
